-- ==========================================
-- CHINOOK SQL PORTFOLIO PROJECT
-- ==========================================
-- 1. Which tracks have a composer listed?
-- Skill: Basic SELECT, filtering
SELECT
	NAME AS TRACK_NAME,
	TRACKID AS TRACK_ID,
	COMPOSER
FROM
	TRACK
WHERE
	COMPOSER IS NOT NULL
LIMIT
	10;

-- 2. What are the highest-valued invoices?
-- Skill: Sorting, LIMIT
SELECT
	INVOICEDATE,
	TOTAL AS INVOICE_TOTAL
FROM
	INVOICE
ORDER BY
	TOTAL DESC
LIMIT
	10;

-- 3. How many tracks are in each genre?
-- Skill: JOINs, GROUP BY, COUNT
SELECT
	G.NAME AS GENRE,
	COUNT(T.TRACKID) AS NUM_TRACKS
FROM
	GENRE G
	JOIN TRACK T ON G.GENREID = T.GENREID
GROUP BY
	G.NAME
ORDER BY
	NUM_TRACKS DESC;

-- 4. Which customers have spent the most money?
-- Skill: JOINs, aggregation, ORDER BY
SELECT
	C.FIRSTNAME || ' ' || C.LASTNAME AS CUSTOMER,
	SUM(I.TOTAL) AS TOTAL_SPEND
FROM
	CUSTOMER C
	JOIN INVOICE I ON C.CUSTOMERID = I.CUSTOMERID
GROUP BY
	C.CUSTOMERID,
	CUSTOMER
ORDER BY
	TOTAL_SPEND DESC
LIMIT
	10;

-- 5. Which artists have the most tracks?
-- Skill: Multi-table JOINs, aggregation
SELECT
	AR.NAME AS ARTIST,
	COUNT(TR.TRACKID) AS TOTAL_TRACKS
FROM
	ARTIST AR
	JOIN ALBUM AL ON AR.ARTISTID = AL.ARTISTID
	JOIN TRACK TR ON AL.ALBUMID = TR.ALBUMID
GROUP BY
	AR.ARTISTID,
	AR.NAME
ORDER BY
	TOTAL_TRACKS DESC;

-- 6. Which customer's total spending exceeds the average total spending?
-- Skill: CTE, aggregation, subquery
WITH
	CUSTOMER_TOTALS AS (
		SELECT
			C.FIRSTNAME || ' ' || C.LASTNAME AS CUSTOMER,
			SUM(I.TOTAL) AS TOTAL_SPEND
		FROM
			CUSTOMER C
			JOIN INVOICE I ON C.CUSTOMERID = I.CUSTOMERID
		GROUP BY
			C.CUSTOMERID,
			CUSTOMER
	)
SELECT
	CUSTOMER,
	TOTAL_SPEND
FROM
	CUSTOMER_TOTALS
WHERE
	TOTAL_SPEND > (
		SELECT
			AVG(TOTAL_SPEND)
		FROM
			CUSTOMER_TOTALS
	)
ORDER BY
	TOTAL_SPEND DESC;

-- 7. Rank customers by total spending per country
-- Skill: Window functions, RANK(), PARTITION BY
SELECT
	C.FIRSTNAME || ' ' || C.LASTNAME AS CUSTOMER,
	C.COUNTRY,
	SUM(I.TOTAL) AS TOTAL_SPENT,
	RANK() OVER (
		PARTITION BY
			C.COUNTRY
		ORDER BY
			SUM(I.TOTAL) DESC
	) AS RANK
FROM
	CUSTOMER C
	JOIN INVOICE I ON C.CUSTOMERID = I.CUSTOMERID
GROUP BY
	C.CUSTOMERID,
	CUSTOMER,
	C.COUNTRY
ORDER BY
	COUNTRY,
	RANK;

-- 8. Which customers have never made a purchase?
-- Skill: LEFT JOIN, filtering NULLs
SELECT
	C.CUSTOMERID,
	C.FIRSTNAME || ' ' || C.LASTNAME AS CUSTOMER
FROM
	CUSTOMER C
	LEFT JOIN INVOICE I ON C.CUSTOMERID = I.CUSTOMERID
WHERE
	I.INVOICEID IS NULL;

-- 9. Which artists have more than 20 tracks?
-- Skill: HAVING clause
SELECT
	AR.NAME AS ARTIST,
	COUNT(T.TRACKID) AS NUM_TRACKS
FROM
	ARTIST AR
	JOIN ALBUM AL ON AR.ARTISTID = AL.ARTISTID
	JOIN TRACK T ON T.ALBUMID = AL.ALBUMID
GROUP BY
	AR.ARTISTID,
	AR.NAME
HAVING
	COUNT(T.TRACKID) > 20
ORDER BY
	NUM_TRACKS DESC;

-- 10. What is the revenue by month?
-- Skill: Date functions, aggregation
SELECT
	DATE_TRUNC('month', INVOICEDATE::TIMESTAMP) AS MONTH,
	SUM(TOTAL) AS REVENUE
FROM
	INVOICE
GROUP BY
	MONTH
ORDER BY
	MONTH;

-- 11. How does cumulative revenue grow over time?
-- Skill: Window functions, SUM() OVER
SELECT
	DATE_TRUNC('month', INVOICEDATE::TIMESTAMP) AS MONTH,
	SUM(TOTAL) AS MONTHLY_REVENUE,
	SUM(SUM(TOTAL)) OVER (
		ORDER BY
			DATE_TRUNC('month', INVOICEDATE::TIMESTAMP)
	) AS RUNNING_TOTAL
FROM
	INVOICE
GROUP BY
	MONTH
ORDER BY
	MONTH;

-- 12. Who are the most valued customers?
-- Skill: CTE, CASE statement for segmentation
WITH
	CUSTOMER_SPEND AS (
		SELECT
			C.CUSTOMERID,
			C.FIRSTNAME || ' ' || C.LASTNAME AS CUSTOMER,
			SUM(I.TOTAL) AS TOTAL_SPEND
		FROM
			CUSTOMER C
			JOIN INVOICE I ON C.CUSTOMERID = I.CUSTOMERID
		GROUP BY
			C.CUSTOMERID,
			CUSTOMER
	)
SELECT
	*,
	CASE
		WHEN TOTAL_SPEND >= 40 THEN 'High Value'
		WHEN TOTAL_SPEND >= 20 THEN 'Medium Value'
		ELSE 'Low Value'
	END AS CUSTOMER_SEGMENT
FROM
	CUSTOMER_SPEND
ORDER BY
	TOTAL_SPEND DESC;

-- 13. Which countries have the highest average order value?
-- Skill: Aggregation, GROUP BY, AVG
SELECT
	BILLINGCOUNTRY AS COUNTRY,
	COUNT(DISTINCT INVOICEID) AS NUM_ORDERS,
	ROUND(AVG(TOTAL), 2) AS AVG_ORDER_VALUE
FROM
	INVOICE
GROUP BY
	BILLINGCOUNTRY
ORDER BY
	AVG_ORDER_VALUE DESC;

-- 14. Top 3 tracks by revenue per genre
-- Skill: Window function + partitioning
WITH
	TRACK_REVENUE AS (
		SELECT
			T.TRACKID,
			T.NAME AS TRACK_NAME,
			G.NAME AS GENRE,
			SUM(IL.UNITPRICE * IL.QUANTITY) AS REVENUE
		FROM
			TRACK T
			JOIN GENRE G ON T.GENREID = G.GENREID
			JOIN INVOICELINE IL ON T.TRACKID = IL.TRACKID
		GROUP BY
			T.TRACKID,
			TRACK_NAME,
			GENRE
	)
SELECT
	*
FROM
	(
		SELECT
			*,
			RANK() OVER (
				PARTITION BY
					GENRE
				ORDER BY
					REVENUE DESC
			) AS RANK
		FROM
			TRACK_REVENUE
	) RANKED
WHERE
	RANK <= 3
ORDER BY
	GENRE,
	RANK;

-- 15. Monthly revenue by country
-- Skill: Multi-dimensional aggregation
SELECT
	C.COUNTRY,
	TO_CHAR(
		DATE_TRUNC('month', I.INVOICEDATE::TIMESTAMP),
		'YYYY-MM'
	) AS MONTH,
	SUM(I.TOTAL) AS MONTHLY_REVENUE
FROM
	INVOICE I
	JOIN CUSTOMER C ON I.CUSTOMERID = C.CUSTOMERID
GROUP BY
	C.COUNTRY,
	MONTH
ORDER BY
	C.COUNTRY,
	MONTH;

-- 16. Most popular media types by number of tracks sold
-- Skill: Multi-table aggregation
SELECT
	MT.NAME AS MEDIA_TYPE,
	COUNT(IL.TRACKID) AS TRACKS_SOLD
FROM
	MEDIATYPE MT
	JOIN TRACK T ON MT.MEDIATYPEID = T.MEDIATYPEID
	JOIN INVOICELINE IL ON T.TRACKID = IL.TRACKID
GROUP BY
	MT.NAME
ORDER BY
	TRACKS_SOLD DESC;